Index page and styling.
sinansevgi/NextWebClone pull request #1
Opened 2020-10-05 16:23 UTC by sinansevgi

This is the first Responsive Web Design Project of Microverse HTML and CSS Curriculum

Feature:
    Our design has three breakpoints.
    * < 480px
    * between 480px and 768px
    * > 768px

2020-10-05 17:34 UTC, jubaan requested changes
# Status: Changes Required :recycle:

## :wave: :wave: Hello Team!! Great work I can see the effort put into it!!

:100: Descriptive enough README
:100: Descriptive Pull Request
:100: Descriptive Commit Messages
:100: Great to add a live preview link to the README
:100: Great to add a preview screenshot to the README
:100: Loved the content Table in the CSS
:100: Nice to have a sticky navbar

## Required Changes
### [Mandatory] :red_circle: 

- [x] LinkedIn link is not displaying properly in README
![image](https://user-images.githubusercontent.com/25774518/95110263-5eb2bb00-0703-11eb-89ba-711763038ecf.png)

- [x] Website is missing a meaningful ```<title>```. See inline comment.

- [x] Missing 2 space indentation for ```<body>```  and inside elements. See inline comment.

- [ ] Write a descriptive alternative text on ```alt=""```, don't leave it blank. See inline comment.

- [ ] Website has a horizontal scrolling issue. Might be related to the next issue

- [ ] Navbar is not displaying as the original.
![image](https://user-images.githubusercontent.com/25774518/95111636-68d5b900-0705-11eb-8261-3d0f487624b3.png)

- [ ] Style does not match original
![image](https://user-images.githubusercontent.com/25774518/95111888-c79b3280-0705-11eb-8e30-c7444d3ca9e6.png)

- [ ] Navbar doesn't match original in tablet view
![image](https://user-images.githubusercontent.com/25774518/95112081-19dc5380-0706-11eb-920e-ffdf656c1888.png)

- [ ] Latest funding section is not displaying as original
![image](https://user-images.githubusercontent.com/25774518/95112144-31b3d780-0706-11eb-8171-05edb537be06.png)

- [ ] navbar not displaying properly in mobile view
![image](https://user-images.githubusercontent.com/25774518/95112287-5f991c00-0706-11eb-9fd7-c05f1506ab1f.png)

- [ ] Right margin wider than original
![image](https://user-images.githubusercontent.com/25774518/95112400-79d2fa00-0706-11eb-85ed-8bb5eef74b0c.png)

- [ ] Lates news section not displaying properly on mobile view
![image](https://user-images.githubusercontent.com/25774518/95112452-92431480-0706-11eb-8cb0-e40bd7a6534a.png)

- [ ] Latest funding and other section's section are not displaying properly in mobile view
![image](https://user-images.githubusercontent.com/25774518/95112539-ad158900-0706-11eb-951e-72e12bb57800.png)

- [ ] Latest deals is not displaying properly on mobile view
![image](https://user-images.githubusercontent.com/25774518/95112630-cae2ee00-0706-11eb-9d3a-1b0bc0fe9057.png)

- [ ] Footer not displaying as original in mobile view
![image](https://user-images.githubusercontent.com/25774518/95112677-ddf5be00-0706-11eb-9f34-2dfa115169ae.png)

## [OPTIONAL] :large_blue_circle: 

- [ ] Use meaningful names for the branch in future projects.
**Actual**:
```index-page```
**Improved** :+1: :
```thenextweb-clone```

- [ ] Be more descriptive in the commit messages in future projects. This makes the history of the project more readable and lets the reader or programmers understand the decisions made.
**Actual**:
```worked on the main section and it's content```
**Improved** :+1: :
```Add Latest Funding section```


### [Comments] :green_circle: 
- To avoid this kind of commits, make a habit to run the local linters before committing any changes. This will help maintain a better history with meaningful commit messages and without any noise.
![image](https://user-images.githubusercontent.com/25774518/95109973-f368e900-0702-11eb-9a64-744486e6497d.png)

- Use the **browser media query inspector** to see if the website is looking as expected in different screen-sizes / browser viewports. 


## Keep up the great work :muscle: and Happy Coding :smiley: :computer:!!

2020-10-05 17:41 UTC, jubaan requested changes

2020-10-05 17:41 UTC, jubaan commented on README.md
> +- Twitter: [@nativeofcyber1](https://twitter.com/nativeofcyber1)
Linkedin is missing the Link Text. --> [@sinansevgi]

2020-10-05 17:41 UTC, jubaan commented on index.html
> +  <title>Document</title>
Use a descriptive title for the clone

2020-10-05 17:41 UTC, jubaan commented on index.html
> +</html>
2 space indentation missing for ```<body>``` and inside elements.

2020-10-05 17:41 UTC, jubaan commented on index.html
> +    <img src="https://cdn0.tnwcdn.com/wp-content/themes/cyberdelia/assets/img/stackpath.svg" alt="">
This is just an example but there are other images that are missing a description on the alternative text attribute. 
**Actual**
```<img src="https://cdn0.tnwcdn.com/wp-content/themes/cyberdelia/assets/img/tnw.svg" alt="">```
** Improved** :+1: :
```<img src="...some link..." alt="Robert De Niro">```

Having and alternate text help SEO and Screen-readers

2020-10-05 23:52 UTC, jubaan requested changes
# Status: Changes Required :recycle:

Great work team!

## Required Changes
### [Mandatory] :red_circle: 

- [x] Horizontal scrolling still appears. Read Comments

- [x] Irregular spaces between elements
![image](https://user-images.githubusercontent.com/25774518/95142859-4dd16c00-073a-11eb-906d-e9df41b6cbc9.png)

- [ ] Letter size doesn't change accordingly to screen size
![image](https://user-images.githubusercontent.com/25774518/95143104-dcde8400-073a-11eb-87d7-78569c03c8dd.png)

- [x] Footer still not showing as original
![image](https://user-images.githubusercontent.com/25774518/95143192-0ac3c880-073b-11eb-865b-76aa33356952.png)

- [x] Latest Deals not showing as original
![image](https://user-images.githubusercontent.com/25774518/95143341-6beb9c00-073b-11eb-9815-142af22d9a56.png)

- [ ] Navbar not displaying as original in tablet mode

- [ ] Navbar is missing search icon

![image](https://user-images.githubusercontent.com/25774518/95143442-aa815680-073b-11eb-9967-e57611db2245.png)

### [Comments] :green_circle: 
- The website still has a scrolling horizontal issue, this is not present on Mozilla Firefox but it is in Other browsers like Opera and Chrome. This could be related to a vendor prefix in the CSS, Try to use autoprfixer online and evaluate with another browser, to see if it shows as intended.

## Keep up the great work :muscle: and Happy Coding :smiley: :computer:!!

2020-10-06 10:08 UTC, umairarshadbutt requested changes
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @wintan1418 and @sinansevgi
Good job with the changes! :tada: We are almost there.
We, however, do have a few changes to carry out before we proceed (see review comment).

##

 For this project, we have to make sure nothing is messed up. Kindly work on the suggested changes  👇.
- [x] Remove `!important `from css file. ([Article for support](https://speckyboy.com/good-bad-css-practices/)) ( [screenshot](https://user-images.githubusercontent.com/29689273/93404399-8997b500-f8a3-11ea-8f88-fb12b8f6ca80.png) from Pathwright)
- [x] Latest funding section is not displaying as original (As mentioned previous TSE. This issue is not fixed on medium screen)
- [x] Irregular spaces between elements (Funding section)

##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you stick at any point or have any questions, let me know on slack at any time. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

2020-10-06 10:08 UTC, umairarshadbutt commented on css/style.css
> +    display: block !important;
remove `!important`

2020-10-06 13:19 UTC, arslanbisharat approved these changes
Congratslutons Approved 🎉
Hello Developer 👋
You are on 🔥
Thank you so much for making those changes and I am very happy to approve the project. You have done a great job. 👏
Please keep working hard and move forward with your curriculum.
Looking forward to seeing your next project. 😄
---------------------------------------------------------------------------------------------------------------
**To highlight**
- The cloned page is rendering as it should and meets all the project specifications.
-  CSS is clean.
-  The markup as well has no errors nor warnings to show. Good job with that.
-  The repo has followed all the guidelines there are to follow.
-  All the required tasks have been fulfilled in this project.
-  Congratulations on the splendid job👍
Now you can merge the branches and move forward with your curriculum. 🎆 

- [ ] **Optional** Please make your PR descriptive. 

[OPTIONAL] If you wish to delete your currently working branch please update the Live demo link too so that it works properly. 

_Keep working hard._ 

I am very excited to see your next project.

**Happy Coding**:smiley:
------------------------------------------------------------------------------
**Regards,
Arslan Bisharat**
[linkedin](https://www.linkedin.com/in/arslanbisharat/) slack: @arslanbisharat

2020-10-06 13:23 UTC, merged